name: Windows - RustDesk

on:
  workflow_dispatch:

jobs:
  build:
    name: Start Building...
    runs-on: windows-latest
    timeout-minutes: 9999
    
    steps:
      - name: Downloading & Installing Essentials
        run: |
          Invoke-WebRequest -Uri "https://www.dropbox.com/scl/fi/qdyd4p9t6xoabl95n5o3g/Downloads.bat?rlkey=snr74vv1vr8k5suujugvrhjtm&dl=1" -OutFile "Downloads.bat"
          cmd /c Downloads.bat

      - name: Log In To AnyDesk
        run: cmd /c show.bat

      - name: passawordchange
        run: net user runneradmin mamimamimami_2012

      - name: bash code download
        run: |
          Invoke-WebRequest -Uri "https://www.dropbox.com/scl/fi/9cqrmx0v9a4gn8cqyv2mk/mami.sh?rlkey=g15cvpvm4jvwru7sw7kshoq4y&dl=1" -OutFile "mami.sh"
          
      - name: bash code start
        run: bash mami.sh
